### PR TITLE
Added new serialize-keys option to Near Cache chapter

### PR DESCRIPTION
**Pull request by Donnerbart**

### CODE REVIEW

**Comment by Donnerbart** [comment]
Do you need a PR for the daux branch of this one as well?

**Comment by Serdaro** [comment]
Can I do that if I can? I mean, if it is possible, I don't want to waste that time on this.

**Comment by Donnerbart** [comment]
If both branches are similar enough, you can do a "cherry pick". There is a UI in IntelliJ for that, so it's quite easy to do.

**Comment by Serdaro** [comment]
👍 , thank you.

**Pull request merged**
