### PR TITLE
Extend Auto Detection description and update setting up clusters with…

### PR DESCRIPTION
**Pull request by leszko**
… discovery plugins

### CODE REVIEW

**Comment by leszko** [comment]
verify

**Comment by leszko** [comment]
verify

**Comment by leszko** [comment]
run-lab-run

**Comment by leszko** [comment]
verify

**Comment by leszko** [comment]
run-lab-run

**Comment by leszko** [comment]
verify

**Comment by leszko** [comment]
Jenkins fails, but I cannot reproduce it locally and nothing meaningful in the logs. @Serdaro , can you help?

**Comment by Serdaro** [comment]
> Jenkins fails, but I cannot reproduce it locally and nothing meaningful in the logs. @Serdaro , can you help?

I don't think it is important, but let me study. Thank you Rafal

**Review by Serdaro — APPROVED** [review]
To be copyedited after merge (minor

**Pull request merged**
