### PR TITLE
Update with note related to #8196

### PR DESCRIPTION
**Pull request by TheBellman**

### CODE REVIEW

**Comment by tombujok** [comment]
Thanks for this PR!

**Comment by Serdaro** [comment]
@TheBellman , Have you signed https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement?preview=/6357071/6619138/Hazelcast%2C%20Inc.%20Individual%20Contrbutor%20License%20Agreement%20v100113.pdf ?

**Comment by TheBellman** [comment]
no, but I can - will get that sorted for you as soon as possible

**Comment by TheBellman** [comment]
Done.

**Comment by Serdaro** [comment]
Thank you so much @TheBellman .

**Pull request merged**
