### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by kwart**

### CODE REVIEW

**Comment by Serdaro** [comment]
@kwart , Do you think it is a good idea to put the Hazelcast IMDG release number attribute into those link texts (so that the attribute retrieves the release number in each release) and after each release I check for unresolved links?

**Comment by kwart** [comment]
I don't want to have results where the links don't work after the manual is generated.

What I would like to see implemented is the following:
* each push into the Hazelcast IMDG `master` or release branch triggers (among OS and EE deployments) also deployment of current documentation;
* documentation deployment builds JavaDoc and ref manual and publish it to some public accessible location (gh-pages or docs.hazelcast.org) under the correct version path (e.g. `4.0-SNAPSHOT`)
* base documentation URL location would be defined within `build.gradle` in a new attribute - sth like `baseUrl` which would reuse the `imdgVersion` attribute. This `baseUrl` would be used within the asciidoc sources.

For final releases, the `baseUrl` would be changed in `build.gradle` to a proper final location on the docs.hazelcast.com

**Comment by kwart** [comment]
Another commit was added. It uses the parametrized documentation URL.

New Jenkins job (http://jenkins.hazelcast.com/job/hazelcast-reference-manual-deployment-master/) is created and configured to be triggered on push into this repository and after deployment of `master` branch in Hazelcast OS.

**Comment by kwart** [comment]
One more thing, among JavaDoc and manual there is also the LinkChecker output generated:
* https://docs.hazelcast.org/docs/4.0-SNAPSHOT/javadoc/
* https://docs.hazelcast.org/docs/4.0-SNAPSHOT/manual/html-single/index.html
* https://docs.hazelcast.org/docs/4.0-SNAPSHOT/linkchecker/

**Pull request merged**
